menu:
  Home: /
  Archives: /archives
  About Matthew: /about
widgets:
- search
- recent_posts

excerpt_link: Read More

twitter:
  username: matthewreily
  show_replies: false
  tweet_count: 5

facebook:
  username: DotNetOk

google_plus:
  username:

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:

comment_provider: disqus
